source "https://rubygems.org"

gem "sinatra"
gem "rack"

gem "rackup", "~> 2.2"
gem "puma", "~> 7.1"
gem "activerecord", "~> 7.1"
gem "sqlite3", "~> 1.7"
gem "rufus-scheduler", "~> 3.9"

group :test do
  gem "rspec", "~> 3.13"
  gem "rack-test", "~> 2.1"
  gem "webmock", "~> 3.19"
  gem "database_cleaner-active_record", "~> 2.1"
end
